SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS sys_error_event (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  error_id VARCHAR(64) NOT NULL,
  trace_id VARCHAR(64),
  source VARCHAR(32) NOT NULL,
  severity VARCHAR(32) NOT NULL,
  fingerprint VARCHAR(64) NOT NULL,
  status_code INT,
  business_code INT,
  message VARCHAR(1000),
  exception_class VARCHAR(255),
  stack_trace MEDIUMTEXT,
  request_method VARCHAR(16),
  request_uri VARCHAR(500),
  query_string VARCHAR(1000),
  request_body_digest VARCHAR(128),
  user_id BIGINT,
  dept_id BIGINT,
  ip_address VARCHAR(64),
  user_agent VARCHAR(500),
  frontend_route VARCHAR(500),
  frontend_component VARCHAR(255),
  frontend_stack MEDIUMTEXT,
  browser_info VARCHAR(1000),
  release_version VARCHAR(64),
  git_commit VARCHAR(64),
  server_name VARCHAR(128),
  resolved TINYINT(1) NOT NULL DEFAULT 0,
  resolved_at DATETIME NULL,
  resolved_by BIGINT,
  remark VARCHAR(1000),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_error_event_error_id (error_id),
  INDEX idx_error_event_created (created_at),
  INDEX idx_error_event_source_created (source, created_at),
  INDEX idx_error_event_severity_created (severity, created_at),
  INDEX idx_error_event_resolved_created (resolved, created_at),
  INDEX idx_error_event_fingerprint (fingerprint, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
